spring.application.name=GoPark
spring.datasource.url=jdbc:mysql://localhost:3306/Proj
spring.datasource.username=root
spring.datasource.password=Firekings@80
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true